// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbnienhgxzekptlwvvpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibmllbmhneHpla3B0bHd2dnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTYyNzgsImV4cCI6MjA2MzY5MjI3OH0.TUUdKqHsA-jS1FeaYjgMrFdwwx66QpBspt1a-Ok9ldI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);